image: Visual Studio 2019
configuration: Release
platform: Any CPU
#install:
#- cmd: git submodule update --init --recursive
build_script:
- cmd: MSBuild -restore /p:Configuration=Release /verbosity:minimal src/TomsToolbox.sln
artifacts:
- path: Deploy/*.nupkg