name: $(Build.DefinitionName) $(date:yyyyMMdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'
  demands:
  - msbuild
  - vstest

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  Solution: 'src\TomsToolbox.sln'

steps:
- task: DeleteFiles@1
  displayName: 'Delete files from Deploy'
  inputs:
    Contents: 'Deploy/**'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(Solution)'

- task: MSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(Solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true

- task: MSBuild@1
  displayName: 'Publish Sample App'
  inputs:
    solution: 'src\SampleApp.Ninject\SampleApp.Ninject.csproj'
    platform: AnyCPU
    configuration: release
    msbuildArguments: '/target:publish'
    logProjectEvents: true
    createLogFile: true
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: VSTest@2
  displayName: 'Test Assemblies **\$(BuildConfiguration)\*test*.dll;-:**\obj\**'
  inputs:
    testAssemblyVer2: |
     **\*test*.dll
     !**\obj\**
    runInParallel: false
    codeCoverageEnabled: false
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    diagnosticsEnabled: True

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Packages'
  inputs:
    SourceFolder: Deploy
    Contents: '*.*'
    TargetFolder: '$(build.artifactstagingdirectory)/Packages'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Sample'
  inputs:
    SourceFolder: src\Publish
    Contents: '*.*'
    TargetFolder: '$(build.artifactstagingdirectory)/Sample'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Packages'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Packages'
    ArtifactName: Packages

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Sample'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Sample'
    ArtifactName: Sample
